"""empty message

Revision ID: 190d90871ae3
Revises: 72a2033e1efd
Create Date: 2018-09-04 12:52:12.905709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190d90871ae3'
down_revision = '72a2033e1efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('comment_to_response', sa.Integer(), nullable=True),
    sa.Column('is_response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comment_to_response'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('comments')
    # ### end Alembic commands ###
